// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lentynaBackEnd.Data;

#nullable disable

namespace lentynaBackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Autoriaus_sekimas", b =>
                {
                    b.Property<Guid>("NaudotojasId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AutoriusId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("sekimo_pradzia")
                        .HasColumnType("datetime(6)");

                    b.HasKey("NaudotojasId", "AutoriusId");

                    b.HasIndex("AutoriusId");

                    b.ToTable("Autoriaus_sekimai");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Autorius", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("curiculum_vitae")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("gimimo_metai")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("knygu_skaicius")
                        .HasColumnType("int");

                    b.Property<string>("laidybe")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("mirties_data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nuotrauka")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("pavarde")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("vardas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Autoriai");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            curiculum_vitae = "Lietuvių rašytojas, poetas, publicistas. Vienas žymiausių lietuvių novelistų.",
                            gimimo_metai = new DateTime(1879, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            knygu_skaicius = 2,
                            mirties_data = new DateTime(1907, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            pavarde = "Biliūnas",
                            vardas = "Jonas"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            curiculum_vitae = "Lietuvių rašytojas, dramaturgas, profesorius. Parašė daug dramų, apsakymų ir romanų.",
                            gimimo_metai = new DateTime(1882, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            knygu_skaicius = 2,
                            mirties_data = new DateTime(1954, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            pavarde = "Krėvė-Mickevičius",
                            vardas = "Vincas"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            curiculum_vitae = "Lietuvių poetas, dramaturgas, literatūros kritikas ir teatro teoretikas.",
                            gimimo_metai = new DateTime(1896, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            knygu_skaicius = 1,
                            mirties_data = new DateTime(1947, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            pavarde = "Sruoga",
                            vardas = "Balys"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            curiculum_vitae = "Šiuolaikinė lietuvių rašytoja, meno istorikė. Garsėja istorinių romanų serija „Silva Rerum",
                            gimimo_metai = new DateTime(1974, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            knygu_skaicius = 2,
                            pavarde = "Sabaliauskaitė",
                            vardas = "Kristina"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            curiculum_vitae = "Anglų rašytojas ir žurnalistas, garsėjantis distopiniais romanais ir socialine kritika.",
                            gimimo_metai = new DateTime(1903, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            knygu_skaicius = 2,
                            mirties_data = new DateTime(1950, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            pavarde = "Orwell",
                            vardas = "George"
                        });
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Balsas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BalsavimasId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KnygaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NaudotojasId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("pateikimo_data")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BalsavimasId");

                    b.HasIndex("KnygaId");

                    b.HasIndex("NaudotojasId");

                    b.ToTable("Balsai");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Balsavimas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("balsavimo_pabaiga")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("balsavimo_pradzia")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("isrinkta_knyga_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("oro_prognoze")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("susitikimo_data")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("uzbaigtas")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("isrinkta_knyga_id");

                    b.ToTable("Balsavimai");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Citata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AutoriusId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("citatos_data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("citatos_saltinis")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("citatos_tekstas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AutoriusId");

                    b.ToTable("Citatos");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Dirbtinio_intelekto_komentaras", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KnygaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("modelis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("sugeneravimo_data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tekstas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("KnygaId");

                    b.ToTable("DI_Komentarai");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Irasas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KnygaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("KnygosRekomendacijaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NaudotojasId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("redagavimo_data")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("sukurimo_data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tipas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("KnygaId");

                    b.HasIndex("KnygosRekomendacijaId");

                    b.HasIndex("NaudotojasId");

                    b.ToTable("Irasai");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Knyga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AutoriusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("aprasymas")
                        .HasColumnType("longtext");

                    b.Property<bool>("bestseleris")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("knygos_pavadinimas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("leidimo_metai")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("psl_skaicius")
                        .HasColumnType("int");

                    b.Property<string>("raisos")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("virselio_nuotrauka")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AutoriusId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Knygos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            AutoriusId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            ISBN = "9785417012345",
                            aprasymas = "Viena garsiausių J. Biliūno novelių apie vargšę mergaitę ir jos sunkų gyvenimą.",
                            bestseleris = false,
                            knygos_pavadinimas = "Liūdna pasaka",
                            leidimo_metai = new DateTime(1907, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            psl_skaicius = 24
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            AutoriusId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            ISBN = "9785417012346",
                            aprasymas = "Novelė apie kaltės jausmą ir žmogaus sąžinę.",
                            bestseleris = false,
                            knygos_pavadinimas = "Kliudžiau",
                            leidimo_metai = new DateTime(1906, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            psl_skaicius = 18
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            AutoriusId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            ISBN = "9785417012347",
                            aprasymas = "Istorinė drama apie Lietuvos kunigaikštį Skirgailą ir jo vidines kovas.",
                            bestseleris = false,
                            knygos_pavadinimas = "Skirgaila",
                            leidimo_metai = new DateTime(1925, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            psl_skaicius = 180
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            AutoriusId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            ISBN = "9785417012348",
                            aprasymas = "Padavimų rinkinys iš Dzūkijos krašto.",
                            bestseleris = false,
                            knygos_pavadinimas = "Dainavos šalies senų žmonių padavimai",
                            leidimo_metai = new DateTime(1912, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            psl_skaicius = 256
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            AutoriusId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            ISBN = "9785417012349",
                            aprasymas = "Memuarai apie autoriaus patirtį Štuthofo koncentracijos stovykloje.",
                            bestseleris = true,
                            knygos_pavadinimas = "Dievų miškas",
                            leidimo_metai = new DateTime(1957, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            psl_skaicius = 320
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            AutoriusId = new Guid("b0000000-0000-0000-0000-000000000004"),
                            ISBN = "9789955234562",
                            aprasymas = "Pirmoji istorinių romanų serijos knyga apie Narvoišių giminę XVII amžiaus Lietuvoje.",
                            bestseleris = true,
                            knygos_pavadinimas = "Silva Rerum",
                            leidimo_metai = new DateTime(2008, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            psl_skaicius = 456
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000007"),
                            AutoriusId = new Guid("b0000000-0000-0000-0000-000000000004"),
                            ISBN = "9789955234563",
                            aprasymas = "Antroji serijos knyga, tęsianti Narvoišių giminės istoriją.",
                            bestseleris = true,
                            knygos_pavadinimas = "Silva Rerum II",
                            leidimo_metai = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            psl_skaicius = 512
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000008"),
                            AutoriusId = new Guid("b0000000-0000-0000-0000-000000000005"),
                            ISBN = "9780451524935",
                            aprasymas = "Distopinis romanas apie totalitarinę visuomenę, kurioje valdžia kontroliuoja kiekvieną gyvenimo aspektą.",
                            bestseleris = true,
                            knygos_pavadinimas = "1984",
                            leidimo_metai = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            psl_skaicius = 328
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000009"),
                            AutoriusId = new Guid("b0000000-0000-0000-0000-000000000005"),
                            ISBN = "9780451526342",
                            aprasymas = "Alegorinė pasaka apie gyvulius, kurie sukyla prieš savo šeimininkus ir bando sukurti lygybės visuomenę.",
                            bestseleris = true,
                            knygos_pavadinimas = "Gyvulių ūkis",
                            leidimo_metai = new DateTime(1945, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            psl_skaicius = 112
                        });
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.KnygaNuotaika", b =>
                {
                    b.Property<Guid>("KnygaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NuotaikaId")
                        .HasColumnType("char(36)");

                    b.HasKey("KnygaId", "NuotaikaId");

                    b.HasIndex("NuotaikaId");

                    b.ToTable("KnygaNuotaikos");

                    b.HasData(
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            NuotaikaId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            NuotaikaId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            NuotaikaId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            NuotaikaId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            NuotaikaId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            NuotaikaId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            NuotaikaId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000008"),
                            NuotaikaId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000009"),
                            NuotaikaId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.KnygaZanras", b =>
                {
                    b.Property<Guid>("KnygaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ZanrasId")
                        .HasColumnType("char(36)");

                    b.HasKey("KnygaId", "ZanrasId");

                    b.HasIndex("ZanrasId");

                    b.ToTable("KnygaZanrai");

                    b.HasData(
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            ZanrasId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            ZanrasId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            ZanrasId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            ZanrasId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            ZanrasId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            ZanrasId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            ZanrasId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            ZanrasId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            ZanrasId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            ZanrasId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000008"),
                            ZanrasId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000008"),
                            ZanrasId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            KnygaId = new Guid("c0000000-0000-0000-0000-000000000009"),
                            ZanrasId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Knygos_rekomendacija", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NaudotojasId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("rekomendacijos_pabaiga")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("rekomendacijos_pradzia")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NaudotojasId");

                    b.ToTable("Knygos_rekomendacijos");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Komentaras", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("KnygaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NaudotojasId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TemaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("komentaro_data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("komentaro_tekstas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("redagavimo_data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("vertinimas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KnygaId");

                    b.HasIndex("NaudotojasId");

                    b.HasIndex("TemaId");

                    b.ToTable("Komentarai");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Naudotojas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("el_pastas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("profilio_nuotrauka")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("slaptazodis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("slapyvardis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("sukurimo_data")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("el_pastas")
                        .IsUnique();

                    b.HasIndex("slapyvardis")
                        .IsUnique();

                    b.ToTable("Naudotojai");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Nuotaika", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("pavadinimas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Nuotaikos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            pavadinimas = "Džiugi"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            pavadinimas = "Liūdna"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            pavadinimas = "Neutrali"
                        });
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Tema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NaudotojasId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("istrynimo_data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("pavadinimas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("prikabinta")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("redagavimo_data")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("sukurimo_data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tekstas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NaudotojasId");

                    b.ToTable("Temos");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Zanras", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("pavadinimas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("pavadinimas")
                        .IsUnique();

                    b.ToTable("Zanrai");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            pavadinimas = "Fantastika"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            pavadinimas = "Detektyvai"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            pavadinimas = "Romanai"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            pavadinimas = "Mokslinė fantastika"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            pavadinimas = "Istoriniai"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            pavadinimas = "Biografijos"
                        },
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            pavadinimas = "Trileriai"
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            pavadinimas = "Poezija"
                        });
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Autoriaus_sekimas", b =>
                {
                    b.HasOne("lentynaBackEnd.Models.Entities.Autorius", "Autorius")
                        .WithMany("Autoriaus_sekimai")
                        .HasForeignKey("AutoriusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lentynaBackEnd.Models.Entities.Naudotojas", "Naudotojas")
                        .WithMany("Autoriaus_sekimai")
                        .HasForeignKey("NaudotojasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autorius");

                    b.Navigation("Naudotojas");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Balsas", b =>
                {
                    b.HasOne("lentynaBackEnd.Models.Entities.Balsavimas", "Balsavimas")
                        .WithMany("Balsai")
                        .HasForeignKey("BalsavimasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lentynaBackEnd.Models.Entities.Knyga", "Knyga")
                        .WithMany("Balsai")
                        .HasForeignKey("KnygaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("lentynaBackEnd.Models.Entities.Naudotojas", "Naudotojas")
                        .WithMany("Balsai")
                        .HasForeignKey("NaudotojasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balsavimas");

                    b.Navigation("Knyga");

                    b.Navigation("Naudotojas");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Balsavimas", b =>
                {
                    b.HasOne("lentynaBackEnd.Models.Entities.Knyga", "IsrinktaKnyga")
                        .WithMany()
                        .HasForeignKey("isrinkta_knyga_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IsrinktaKnyga");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Citata", b =>
                {
                    b.HasOne("lentynaBackEnd.Models.Entities.Autorius", "Autorius")
                        .WithMany("Citatos")
                        .HasForeignKey("AutoriusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autorius");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Dirbtinio_intelekto_komentaras", b =>
                {
                    b.HasOne("lentynaBackEnd.Models.Entities.Knyga", "Knyga")
                        .WithMany("DI_Komentarai")
                        .HasForeignKey("KnygaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knyga");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Irasas", b =>
                {
                    b.HasOne("lentynaBackEnd.Models.Entities.Knyga", "Knyga")
                        .WithMany("Irasai")
                        .HasForeignKey("KnygaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lentynaBackEnd.Models.Entities.Knygos_rekomendacija", "Knygos_rekomendacija")
                        .WithMany("Irasai")
                        .HasForeignKey("KnygosRekomendacijaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("lentynaBackEnd.Models.Entities.Naudotojas", "Naudotojas")
                        .WithMany("Irasai")
                        .HasForeignKey("NaudotojasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knyga");

                    b.Navigation("Knygos_rekomendacija");

                    b.Navigation("Naudotojas");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Knyga", b =>
                {
                    b.HasOne("lentynaBackEnd.Models.Entities.Autorius", "Autorius")
                        .WithMany("Knygos")
                        .HasForeignKey("AutoriusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autorius");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.KnygaNuotaika", b =>
                {
                    b.HasOne("lentynaBackEnd.Models.Entities.Knyga", "Knyga")
                        .WithMany("KnygaNuotaikos")
                        .HasForeignKey("KnygaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lentynaBackEnd.Models.Entities.Nuotaika", "Nuotaika")
                        .WithMany("KnygaNuotaikos")
                        .HasForeignKey("NuotaikaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knyga");

                    b.Navigation("Nuotaika");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.KnygaZanras", b =>
                {
                    b.HasOne("lentynaBackEnd.Models.Entities.Knyga", "Knyga")
                        .WithMany("KnygaZanrai")
                        .HasForeignKey("KnygaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lentynaBackEnd.Models.Entities.Zanras", "Zanras")
                        .WithMany("KnygaZanrai")
                        .HasForeignKey("ZanrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knyga");

                    b.Navigation("Zanras");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Knygos_rekomendacija", b =>
                {
                    b.HasOne("lentynaBackEnd.Models.Entities.Naudotojas", "Naudotojas")
                        .WithMany("Knygos_rekomendacijos")
                        .HasForeignKey("NaudotojasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Naudotojas");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Komentaras", b =>
                {
                    b.HasOne("lentynaBackEnd.Models.Entities.Knyga", "Knyga")
                        .WithMany("Komentarai")
                        .HasForeignKey("KnygaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("lentynaBackEnd.Models.Entities.Naudotojas", "Naudotojas")
                        .WithMany("Komentarai")
                        .HasForeignKey("NaudotojasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lentynaBackEnd.Models.Entities.Tema", "Tema")
                        .WithMany("Komentarai")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Knyga");

                    b.Navigation("Naudotojas");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Tema", b =>
                {
                    b.HasOne("lentynaBackEnd.Models.Entities.Naudotojas", "Naudotojas")
                        .WithMany("Temos")
                        .HasForeignKey("NaudotojasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Naudotojas");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Autorius", b =>
                {
                    b.Navigation("Autoriaus_sekimai");

                    b.Navigation("Citatos");

                    b.Navigation("Knygos");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Balsavimas", b =>
                {
                    b.Navigation("Balsai");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Knyga", b =>
                {
                    b.Navigation("Balsai");

                    b.Navigation("DI_Komentarai");

                    b.Navigation("Irasai");

                    b.Navigation("KnygaNuotaikos");

                    b.Navigation("KnygaZanrai");

                    b.Navigation("Komentarai");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Knygos_rekomendacija", b =>
                {
                    b.Navigation("Irasai");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Naudotojas", b =>
                {
                    b.Navigation("Autoriaus_sekimai");

                    b.Navigation("Balsai");

                    b.Navigation("Irasai");

                    b.Navigation("Knygos_rekomendacijos");

                    b.Navigation("Komentarai");

                    b.Navigation("Temos");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Nuotaika", b =>
                {
                    b.Navigation("KnygaNuotaikos");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Tema", b =>
                {
                    b.Navigation("Komentarai");
                });

            modelBuilder.Entity("lentynaBackEnd.Models.Entities.Zanras", b =>
                {
                    b.Navigation("KnygaZanrai");
                });
#pragma warning restore 612, 618
        }
    }
}
